<?php

use Illuminate\Database\Seeder;

class CompanyPickupTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        // batch 1
        // DB::statement("
        //     SET IDENTITY_INSERT companies ON;
        //     INSERT companies(id, name)
        //     VALUES(9, 'LASALA EVERBRIGHT COMMERCIAL'),
        //     (10, 'LVT FREIGHT FORWARDERS, INC.'),
        //     (11, 'STANDARD INSURANCE CO. INC.'),
        //     (12, 'ANA J. VISITACION'),
        //     (13, 'R-II BUILDERS'),
        //     (14, 'MAERSK FILIPINAS, INC.'),
        //     (15, 'ACCENT MICRO TECHNOLOGIES, INC.'),
        //     (16, 'N.V. REAŇO CUSTOMS BROKARAGE'),
        //     (17, 'ENERZA M. LOZANO TRADING'),
        //     (18, 'R.J. LIMCAOCO TRANSPORT'),
        //     (19, 'MOF COMPANY, INC.'),
        //     (20, 'CORE SCIENTIFIC INDUSTRIES'),
        //     (21, 'SOUTHBAY TOOLING CORPORATION'),
        //     (22, 'LINSTAR MECHANICAL SYSTEM INC.'),
        //     (23, 'DIVERSIFIED PEST SOLUTIONS, INC.'),
        //     (24, 'WILL-YO-MAR JUNK SHOP'),
        //     (25, 'EDJET TRADING'),
        //     (26, 'PAVIA TRADING'),
        //     (27, 'SUAZO, VICENTE JR'),
        //     (28, 'ASALUS CORPORATION'),
        //     (29, 'PHILIPPINE LEADING INFINITE'),
        //     (30, 'WATERS UNLIMITED, INC.'),
        //     (31, 'AMIGO LOGISTICS CORPORATION'),
        //     (32, 'MIKS TRADING'),
        //     (33, 'IDEAL VISION CENTER'),
        //     (34, 'DONNABELLE PASQUIN'),
        //     (35, 'PO, ALEXANDER JOHN'),
        //     (36, 'ANTIPORDA, ANBRIE B.'),
        //     (37, 'FELICIO, FAYE C.'),
        //     (38, 'ABUGAN, JOVY M.'),
        //     (39, 'GOGO, LUIS ALFONSO C.'),
        //     (40, 'LA FILIPINA MEATS, INC.'),
        //     (41, 'MINDANAO GRAIN PROCESSING CO., INC.'),
        //     (42, 'ADVANCED AGRISOLUTIONS PHILS CORP.'),
        //     (43, 'RESEARCH AND DEVELOPMENT DEPT'),
        //     (44, '88 HARVEST BAKERY SUPPLIE'),
        //     (45, 'A-1 AGRO FERTILIZER  AND CH'),
        //     (46, 'ABRI COMMERCIAL INC.'),
        //     (47, 'AGC BAKERIES INC.'),
        //     (48, 'AJINOMOTO PHILIPPINES COR'),
        //     (49, 'ONG AMADO'),
        //     (50, 'AMARELA, INC.'),
        //     (51, 'ANAGENE ENTERPRISE'),
        //     (52, 'ANGELES FILIPINO ENTERPRI'),
        //     (53, 'AUTHORITY TRADING CORP.'),
        //     (54, 'B8 BREADSTOP AND GROCERY'),
        //     (55, 'BAKEMASTERS, INC.'),
        //     (56, 'BAKERSON MARKETING CORPOR'),
        //     (57, 'BARDSTOWN, INC.'),
        //     (58, 'CAFEFRANCE CORP.'),
        //     (59, 'CERES STAR MARKETING'),
        //     (60, 'CESTA DE PAN CORPORATION'),
        //     (61, 'HANSBAKE MARKETING CORPOR'),
        //     (62, 'UNILUCK FOOD PRODUCTS'),
        //     (63, 'CONTEMPORAIN FOODS INC.'),
        //     (64, 'CROWN PRIME ASIA CORPORAT'),
        //     (65, 'DEL MONTE PHILIPPINES, IN'),
        //     (66, 'DONG-A PHARMA PHILS INC.'),
        //     (67, 'DOUGHPRO MANUFACTURING AND'),
        //     (68, 'MANCHESTER TRADING'),
        //     (69, 'SANAGA FLOUR TRADING'),
        //     (70, 'SHOP AND BAKE ENTERPRISE'),
        //     (71, 'EBG SUPERMARKET STORES CO'),
        //     (72, 'EFC FOOD CORPORATION'),
        //     (73, 'EVERYDAY FRAYCHEUR CORP.'),
        //     (74, 'FOOD INDUSTRIES'),
        //     (75, 'FOODFLOW INC.'),
        //     (76, 'FOODSPHERE INC.'),
        //     (77, 'FRESH N FAMOUS FOODS INC - CHOWKIN'),
        //     (78, 'FRESH N FAMOUS FOODS INC - GREENWI'),
        //     (79, 'GARDENIA BAKERIES PHILS.'),
        //     (80, 'GEOCON MARKETING'),
        //     (81, 'GLOBAKE CORPORATION'),
        //     (82, 'GLORY GENERAL MERCHANDISE'),
        //     (83, 'THE FRENCH BAKER, INC.'),
        //     (84, 'CONTAINER CORP. OF THE PH'),
        //     (85, 'GOLDEN FINN AND JOSEPH INCO'),
        //     (86, 'GOLDEN PANDESAL, INC.'),
        //     (87, 'GOLDILOCKS BAKESHOP, INC.'),
        //     (88, 'GREENSTONE  PACKAGING COR'),
        //     (89, 'HOPIA KING BAKERY'),
        //     (90, 'INTERBAKE MARKETING CORP.'),
        //     (91, 'INTERNATIONAL FAMILY FOOD'),
        //     (92, 'J.S.  SANTIAGO STORE'),
        //     (93, 'JAMS BAKELAND FOODS, INC.'),
        //     (94, 'LA NOCEDA ENTERPRISE'),
        //     (95, 'LARTIZAN CORPORATION'),
        //     (96, 'LIBERTY FOODMART, INC.'),
        //     (97, 'LIWAYWAY MARKETING CORPOR'),
        //     (98, 'MEGA GOLDTOWN PAN, INC.'),
        //     (99, 'NORTH PARK NOODLE HOUSE,'),
        //     (100, 'PAN DE MANILA FOOD CO INC'),
        //     (101, 'PRIME PBS BAKERY SUPPLY'),
        //     (102, 'Q. PHILIPPINE PRODUCTS IN'),
        //     (103, 'QWIKBREAD CORPORATION'),
        //     (104, 'RELISH BAKING SPECIALIST'),
        //     (105, 'RUDY-BECCA COMENDADOR STO'),
        //     (106, 'LAMITEK SYSTEMS, INCORPOR'),
        //     (107, 'SANTEH FEEDS CORP'),
        //     (108, 'GREENKRAFT CORPORATION'),
        //     (109, 'SIR DINKS FOOD PRODUCTS,'),
        //     (110, 'STANBAKE MARKETING CORPOR'),
        //     (111, 'SULHEN AND TJJ CORPORATION'),
        //     (112, 'WELL-PACK CONTAINER CORPORATION'),
        //     (113, 'BATANGAS PAPER CORPORATIO'),
        //     (114, 'GRACELAND FOOD INDUSTRIES'),
        //     (115, 'TEAMBAKE MARKETING CORPOR'),
        //     (116, 'TEDDY AND EDITH GENERAL MER'),
        //     (117, 'THE REAL AMERICAN DOUGHNU'),
        //     (118, 'UNIQUE MOSIMO TRADING COR'),
        //     (119, 'VJL MARKETING COMPANY'),
        //     (120, 'WAFFLE TIME INC.'),
        //     (121, 'JMV ENTERPRISE'),
        //     (122, 'CHA-CHAS PIZZA HOUSE'),
        //     (123, 'SALENTO FOOD CORPORATION'),
        //     (124, 'NUEVA VIZCAYA RISING SONS'),
        //     (125, 'DREAM HIGH MARKETING'),
        //     (126, 'SUNCREST FOODS INCORPORAT'),
        //     (127, 'LINKAGE FOODS VENTURE COR'),
        //     (128, 'SAN PABLO BAKERY'),
        //     (129, 'TEAMBAKE MARKETING'),
        //     (130, 'F. CARANDANG STORE'),
        //     (131, 'REBANAS FOOD PRODUCTS'),
        //     (132, 'INTERNATIONAL FAMILY FOD SERVICES'),
        //     (133, 'NORTHPOINT BAKERY AND GEN MDSE'),
        //     (134, 'LITTLE SAINTS BAKERY'),
        //     (135, 'PINEYARD MARKETING'),
        //     (136, 'NUTRISNACK (NUTRITIVE SNACK FOOD'),
        //     (137, 'LOTS A PIZZA'),
        //     (138, 'MONDE NISSIN CORPORATION'),
        //     (139, 'PANNYS HOMEBAKE PRODUCT'),
        //     (140, 'PARK AND GO-CABANCALAN'),
        //     (141, 'PARK AND GO-HERNAN, CORTEZ'),
        //     (142, 'PARK AND GO-LARENA'),
        //     (143, 'PARK AND GO-SINGSON'),
        //     (144, 'PARK AND GO-TIPOLO'),
        //     (145, 'CHERAPH FOOD CORP.'),
        //     (146, 'CLEMENS BREAD EXPRESS'),
        //     (147, 'BEAS BREAD BASKET'),
        //     (148, 'BREAD MASTER BAKESHOP'),
        //     (149, 'HEALTH FOODS FACTORY'),
        //     (150, 'LOLO TINONG'),
        //     (151, 'MOMMY LOUS BAKESHOP'),
        //     (152, 'SR. SAN JOSE FRANCHISING'),
        //     (153, 'ALARDE, ARSENIO'),
        //     (154, 'CRUZ, TITA'),
        //     (155, 'ONG KIN KING AND CO., INC.'),
        //     (156, 'STO. NIÑO BAKERY AND ICE CREAM SUPPLY'),
        //     (157, 'GENE SALVARO DE CEBU'),
        //     (158, 'LENNYS BAKESHOP'),
        //     (159, 'New Goodly Mercantile'),
        //     (160, 'JOSE SANTOS'),
        //     (161, 'MEGA GOLD TOWN PAN INC.'),
        //     (162, 'MUY BIEN PANADERIA'),
        //     (163, 'AL RAZON FOODS CORPORATIO'),
        //     (164, 'H.A. GALANG AND SONS, IN.'),
        //     (165, 'HEALTHY FOODS FACTORY'),
        //     (166, 'CGE'),
        //     (167, 'VILMAR FERRER'),
        //     (168, 'GERALD CAMAGAN'),
        //     (169, 'ZENITH FOODS CORPORATION'),
        //     (170, 'STOP OVER BAKESHOP, INC.'),
        //     (171, 'PERCYS BAKESHOP'),
        //     (172, 'OBLIGADO, ALFREDO'),
        //     (173, 'SALES, BEN'),
        //     (174, 'DOC-DOC STORE'),
        //     (175, 'EDWIN STORE'),
        //     (176, 'EM MKTG.'),
        //     (177, 'ERWIN BAKESHOP'),
        //     (178, 'G-STORE'),
        //     (179, 'LOREN STORE'),
        //     (180, 'ONG, MARTIN'),
        //     (181, 'ROGER BAKESHOP'),
        //     (182, 'TOMAS STORE'),
        //     (183, 'PARK AND GO-BONIFACIO,ORMOC'),
        //     (184, 'PARK AND GO-ISABEL'),
        //     (185, 'PARK AND GO-NAVAL'),
        //     (186, 'PARK AND GO-PALOMPON'),
        //     (187, 'PASESAR TRADING'),
        //     (188, 'ADAMO AGRITURISMO, INC.'),
        //     (189, 'LENM MARKETING'),
        //     (190, 'SOUTHGATE EXPRESS MKTG.,'),
        //     (191, 'NEW YAN YAN COMMERCIAL'),
        //     (192, 'KRIS V BAKERY'),
        //     (193, 'GREATWALL MERCHANDISE'),
        //     (194, 'MALVAR TRADING'),
        //     (195, 'NEW POLLYNS GROCERY'),
        //     (196, 'GO GRO CORPORATION'),
        //     (197, 'VK BAKERY'),
        //     (198, 'RED RIBBON BAKESHOP INC.'),
        //     (199, 'PARK AND GO-SEQUIJOR'),
        //     (200, 'ALTURAS SUPERMART CORPORATION'),
        //     (201, 'THE STEAMSHOP SIOPAO AVENUE, INC.'),
        //     (202, 'BATANGAS PAPER CORP'),
        //     (203, 'CLAY AND CHAZ TRADING CORP.'),
        //     (204, 'NORTHERN TRADING'),
        //     (205, 'SOUTH SEA'),
        //     (206, 'SAN ANTONIO MARKETING'),
        //     (207, 'ROGER TRADING INCORPORA'),
        //     (208, 'TRIPLE STAR PACKAGING COR'),
        //     (209, 'REL MARKETING'),
        //     (210, 'ROGER TRADING, INC'),
        //     (211, 'ILOILO LOS FILIPINOS BAKE'),
        //     (212, 'TERESITA BRETANA'),
        //     (213, 'NOLIE CALFOFORO'),
        //     (214, 'FLORENCE FLORES'),
        //     (215, 'MIGUEL BRIETO'),
        //     (216, 'NEW MASTER BAZAR'),
        //     (217, 'GOLD STAR TRADERS'),
        //     (218, 'SWEETREATS INC.'),
        //     (219, 'REGENCY LAGOON RESORT, IN'),
        //     (220, 'SERAPH MANAGEMENT GROUP,'),
        //     (221, 'BORACAY MANDARIN'),
        //     (222, 'BORACAY MINI MART'),
        //     (223, 'MEGA GOLD TOWN PAN, INC.'),
        //     (224, 'FRONTLAKE, INC.'),
        //     (225, 'SIETE MARIAS BAKERY AND GRO'),
        //     (226, 'LA FUERZA BAKESHOP AND GROC'),
        //     (227, 'CENTERPOINT PLASTIC CENTE'),
        //     (228, 'CAKES EAT CETERA'),
        //     (229, 'SUPER BAKER INC.'),
        //     (230, 'NICE AND WISE CONVENIENT ST'),
        //     (231, 'LUMOGDANG, JANETT'),
        //     (232, 'CN MARKETING'),
        //     (233, 'NEW STAR APA CORPORATION'),
        //     (234, 'CHIN HONG COMMERCIAL'),
        //     (235, 'KINGLY TRADING'),
        //     (236, 'YKS TRADING'),
        //     (237, 'SANVIC ENTERPRISE'),
        //     (238, 'TACLOBAN GOODWILL COMMERC'),
        //     (239, 'DIPOLOG CENTRAL TRADING AND GEN.'),
        //     (240, 'RIVSON DIPOLOG MERCHANDIZING'),
        //     (241, 'AF STORE'),
        //     (242, 'BASIC KNEAD MART'),
        //     (243, 'GRAND MEGA INC.'),
        //     (244, 'HONG BEE TRADING'),
        //     (245, 'LB SUPERMARKET'),
        //     (246, 'NEW SEN HUA COMMERCIAL'),
        //     (247, 'NEW SITANGKAI SHOPPER CHOICE'),
        //     (248, 'ODJ ENTERPRISE'),
        //     (249, 'ONG SIOK DIAN STORE'),
        //     (250, 'E.D SALES CENTER'),
        //     (251, 'ZAMBOANGA BAKERY'),
        //     (252, 'ZAMBOANGA GRAIN MART 2'),
        //     (253, 'ZAMBOANGA GRAIN MART 1'),
        //     (254, 'AHG AGRI-VENTURES'),
        //     (255, 'CENTRO SUPERSALES'),
        //     (256, 'NENE UY STORE'),
        //     (257, 'RED RIBBON BAKESHOP, INC.'),
        //     (258, 'SEVENTY SEVEN CONSUMER SALES'),
        //     (259, 'SILVER LIGHTS BAKERY'),
        //     (260, 'KUROIKEBU FOOD INC.'),
        //     (261, 'LESLIE CORPORATION'),
        //     (262, 'LINKAGE FOODS VENTURE CORPORATION'),
        //     (263, 'LTS CITY FOODS, INC.'),
        //     (264, 'R.D.V. FOOD INDUSTRIES'),
        //     (265, 'ROOKIES FRUIT PRESERVES CORPORATION'),
        //     (266, 'EARTH GRAIN, INC.'),
        //     (267, 'ACH CORPORATION'),
        //     (268, 'APH MARKETING'),
        //     (269, 'COTABATO CENTERPOINT INC.'),
        //     (270, 'COTABATO FISH TRADING CO. INC.'),
        //     (271, 'COTABATO FOOD CENTER'),
        //     (272, 'LANSH ENTERPRISES CENTER'),
        //     (273, 'SUPERAMA SUPERMART AND PHARMACY'),
        //     (274, 'VKO MARKETING'),
        //     (275, 'JSDR MARKETING'),
        //     (276, 'BUTUAN GOLDEN KEY CORPORATION'),
        //     (277, 'GLOBAL FOODS DISTRIBUTION CORP.'),
        //     (278, 'NEW ANG GROCERY'),
        //     (279, 'SURIGAO TOPPERS MULTI-SALES, INC.'),
        //     (280, 'ANALOU BREADHAUS'),
        //     (281, 'FONDRE FLAVOUR DYNAMICS INC.'),
        //     (282, 'ANGEL OF JL FOOD INDUSTRIES'),
        //     (283, 'PAN DE MANILA FOOD CO., INC.'),
        //     (284, 'MIX PLANT, INC.'),
        //     (285, 'GRAND PROSPERITY'),
        //     (286, 'AMON-R8 COMMERCIAL INC.'),
        //     (287, 'RUBEN BAKESHOP'),
        //     (288, 'VIRGINIA STORE'),
        //     (289, 'GREENSTONE PACKAGING CORP.'),
        //     (290, 'VJL MARKETING CORP.'),
        //     (291, 'GYOZA SPECIALIST INC'),
        //     (292, 'G-DITHS TRADING'),
        //     (293, 'KOOKEEHOUSE INC.'),
        //     (294, 'NORTHPOINT, INC.'),
        //     (295, 'CERESTAR MARKETING'),
        //     (296, 'CESTA DE LUCIA STORE'),
        //     (297, 'CACNIO, JAIME'),
        //     (298, 'RANARIO, JOHN JEROME'),
        //     (299, 'QUICK SOURCE COMMODITIES CORP.'),
        //     (300, 'ROGER TRADING INCORPORATED'),
        //     (301, 'TRIPLE STAR PACKAGING CORP.'),
        //     (302, 'PEOPLES AGRI KUBO TRADING'),
        //     (303, 'BAKER PERCENT'),
        //     (304, '818 EAST ASIA GROUP CORP.'),
        //     (305, 'GREENSTONE JENEFHIER QUINO/JENNY'),
        //     (306, 'RICHBAKE, INC.'),
        //     (307, 'JENNSON PACKAGING CORPORATION'),
        //     (308, 'AMIGO AGRO-INDUSTRIAL DEV'),
        //     (309, 'LA FILIPINA UY GONGCO CORP. (MLA)'),
        //     (310, 'EXCEL FARM CORPORATION'),
        //     (311, '3S FOODS INDUSTRIES'),
        //     (312, 'A-1 AGRO FERTILIZER  AND CHEMICAL'),
        //     (313, 'A.S. ALVAR ENTERPRISES'),
        //     (314, 'AGBAYANI FREIGHT SERVICES CORP.'),
        //     (315, 'AJINOMOTO PHILIPPINES CORPORATION'),
        //     (316, 'ALLIANCE COMMODITIES CENTER, INC.'),
        //     (317, 'ALMA STORE'),
        //     (318, 'AMPO ENTERPRISES'),
        //     (319, 'ANCEL PURE VEG. COOKING OIL AND BAKER'),
        //     (320, 'ANGELES FILIPINO ENTERPRISES'),
        //     (321, 'ANGELES JOHNNY SUPERMARKET, INC.'),
        //     (322, 'BAKER CHUM MARKETING'),
        //     (323, 'BAKER FAIR AND FOODMART'),
        //     (324, 'BAKERS HAT INC.'),
        //     (325, 'BAKERSON MARKETING CORPORATION'),
        //     (326, 'BARRIO FIESTA MANUFACTURING CORPORA'),
        //     (327, 'BEATRICE KITCHEN, INC.'),
        //     (328, 'BETTY ORTIGAS'),
        //     (329, 'BOSTON MEGA TRANSPORT'),
        //     (330, 'BUSINESS PRIME ENTERPRISES,  INC.'),
        //     (331, 'C.R. SANCHEZ GENERAL SERVICES'),
        //     (332, 'C.V.I. BAKERY SUPPLY'),
        //     (333, 'CAKE DECOR MARKETING'),
        //     (334, 'CANDYLINE FOOD MANUFACTURING'),
        //     (335, 'CANELLE FOOD CORPORATION'),
        //     (336, 'CAPIZ SUGAR CENTRAL, INC.'),
        //     (337, 'CARLA BAKERY AND CONFECTIONERY SUPP'),
        //     (338, 'CASTLEMAINE CORP'),
        //     (339, 'CELSO RICE RETAILER'),
        //     (340, 'CENTENNIAL FOOD CORP.'),
        //     (341, 'CEREAL FOODS CORPORATION'),
        //     (342, 'CHARING MERCHANDISING'),
        //     (343, 'CHOCO-VRON BAKESHOP '),
        //     (344, 'CHRISTINE L. MUNOZ'),
        //     (345, 'CKRV TRUCKING AND TRADING'),
        //     (346, 'CLARMIL MANUFACTURING, INC.'),
        //     (347, 'CLASSIC BAKER CORPORATION'),
        //     (348, 'CLEMENTE L. SANTIAGO TRUCKING'),
        //     (349, 'COLUMBIA INTERNATIONAL FOOD'),
        //     (350, 'CONCEPCION CONSUMERS MARKETING'),
        //     (351, 'CONTAINER CORP. OF THE PHIL.'),
        //     (352, 'CROLEY FOODS'),
        //     (353, 'CZARENAH ENTERPRISES'),
        //     (354, 'D AND C TRADING'),
        //     (355, 'DELLY BAKERY SUPPLY'),
        //     (356, 'D AND H ENTERPRISES'),
        //     (357, 'DY TRANSPORT SERVICES'),
        //     (358, 'E.P. CASTILLO, JR. GENERAL MERCHAND'),
        //     (359, 'EDWARD KELLER (PHILS.) INC.'),
        //     (360, 'ELISA D. NEMIS PIZZA HAUS'),
        //     (361, 'ELIZABETH BAKERY AND GROCERY'),
        //     (362, 'ENG BEE TIN'),
        //     (363, 'ENOY GROCERY AND BAKERY SUPPLY'),
        //     (364, 'EOC FOOD INDUSTRIES'),
        //     (365, 'EQUALIVET, INC.'),
        //     (366, 'ERVIN REY'),
        //     (367, 'ERWIN K. PENA GENERAL MERCHANDISE'),
        //     (368, 'EVERLASTING GROCERY'),
        //     (369, 'EXAL RICE AND POULTRY SUPPLY'),
        //     (370, 'FERABBY MERCANTILE, INCORPORATED'),
        //     (371, 'FIL-TREPRENEUR FRANCHISE INC.'),
        //     (372, 'FFFI FILIPINO FOOD FAVORITES, INC.'),
        //     (373, 'FIRST EL PRESIDENTE MFG., INC.'),
        //     (374, 'FRABELLE MARKET CORPORATION'),
        //     (375, 'FRAMES STORE'),
        //     (376, 'FREA TRADING'),
        //     (377, 'FRESH N FAMOUS FOODS INC.'),
        //     (378, 'GAB STORE'),
        //     (379, 'GARDENIA BAKERIES (PHILS.) INC.'),
        //     (380, 'GCH INTERNATIONAL MERCANTILE, INC.'),
        //     (381, 'GERVI BAKERY'),
        //     (382, 'GLORIA STORE'),
        //     (383, 'GOMICO FOOD INC.'),
        //     (384, 'GOODWILL COMMERCIAL'),
        //     (385, 'GRAND ALPHATECH INTERNATIONAL'),
        //     (386, 'GREENBELT FOOD PRODUCTS CORPORATION'),
        //     (387, 'GREENSTONE  PACKAGING CORP.'),
        //     (388, 'GSJ TRADING'),
        //     (389, 'H-II GRAINS PLASTICS AND BAKERY'),
        //     (390, 'HAMBUDY FOOD CO.'),
        //     (391, 'HANSBAKE MARKETING CORPORATION'),
        //     (392, 'HOC GUAN MANUFACTURING CORP.'),
        //     (393, 'IFMC(IMELDA FELIZARDO MELROSE CLER)'),
        //     (394, 'ILOCOS BAKESHOP'),
        //     (395, 'INDOFINE INTERNATIONAL'),
        //     (396, 'INNA MARIE PANDESAL'),
        //     (397, 'INNOVATIVE STAR RECIPES, INC.'),
        //     (398, 'INTERNATIONAL FAMILY FOOD SERVICES'),
        //     (399, 'INVENTS TALENT AND EVENT MANAGEMENT'),
        //     (400, 'IVY AND ICY BAKESHOP'),
        //     (401, 'IZUMMI SNACKS CORPORATION'),
        //     (402, 'JACQUELINE GROCERY'),
        //     (403, 'JAMELINA BAKERY AND GENERAL'),
        //     (404, 'JHAYE ALLISON CEREAL CENTRE'),
        //     (405, 'JLG MARKETING'),
        //     (406, 'JOHNNY LI WAN YU'),
        //     (407, 'JOSIE BAKERY'),
        //     (408, 'JVP BREAD KING FOOD CORP.'),
        //     (409, 'JVSY MARKETING'),
        //     (410, 'KBC'),
        //     (411, 'KELGENE INTERNATIONAL INC.'),
        //     (412, 'KGM GENERAL MERCHANDISING'),
        //     (413, 'KILLION MERCHANDISING'),
        //     (414, 'KILPATRICKS, CORP.'),
        //     (415, 'KOOKEEHOUSE, INC.'),
        //     (416, 'LA PACITA BISCUIT'),
        //     (417, 'LAMITEK SYSTEMS, INCORPORATED'),
        //     (418, 'LEEGON MARKETING'),
        //     (419, 'LEHIGH TRUCKING SERVICES'),
        //     (420, 'LEMON MERCHANDISING'),
        //     (421, 'LES ORIENT CHEMICAL ENTERPRISE CO.'),
        //     (422, 'LESLIE FARMS, INC.'),
        //     (423, 'LIANA TRADING'),
        //     (424, 'LIONGSON BAKERY SUPPLY'),
        //     (425, 'LIWAYWAY MARKETING CORPORATION'),
        //     (426, 'MABINI BAKERY AND ICE CREAM SUPPLY'),
        //     (427, 'MABUHAY BISCUIT CORPORATION'),
        //     (428, 'MALABANAN GENEROSO ENTERPRISES'),
        //     (429, 'MANUEL R. FLORES'),
        //     (430, 'MAR - V - RITZ TRADING - BRANCH'),
        //     (431, 'MAR-SHIE AGRICULTURAL, POULTRY SUPP'),
        //     (432, 'MARBY FOOD VENTURES CORP.'),
        //     (433, 'MASTER TOUCH FOUNDATION, INC.'),
        //     (434, 'MAX BAKESHOP, INC.'),
        //     (435, 'MB SUMMIT TRADING CORP.'),
        //     (436, 'MEGAPACK CONTAINER CORP.'),
        //     (437, 'MENRUZ TRUCKING SERVICES, INC.'),
        //     (438, 'MERCY BREAD HOUSE'),
        //     (439, 'MERRIAM BRETA F'),
        //     (440, 'MERT AND SHIRLEY GROCERY STORE'),
        //     (441, 'MICHELL CAKES AND PASTRIES'),
        //     (442, 'MIMIPAN BAKESHOP'),
        //     (443, 'MINDORO SAGANA MERCHANDISING, INCOR'),
        //     (444, 'MONDE M.Y. SAN CORPORATION'),
        //     (445, 'MONTON MARKETING'),
        //     (446, 'MSJ TRADING'),
        //     (447, 'MULTIRICH FOODS CORPORATION'),
        //     (448, 'MZL TRUCKING'),
        //     (449, 'NATHANIEL BAKESHOP'),
        //     (450, 'NEW BUTTERWORLD BAKESHOP'),
        //     (451, 'NEW FOOD COATING INC.'),
        //     (452, 'NEW HERITAGE BAKERY'),
        //     (453, 'NEW JOHNSON SUPERMART'),
        //     (454, 'NEW LONG LIFE BAKERY'),
        //     (455, 'NEW POLLAND BAKER FAIR'),
        //     (456, 'NIDHAN FLOUR GRINDING SERVICES'),
        //     (457, 'NISO MARKETING'),
        //     (458, 'NORMAN AGUILAN CORVITE GENERAL MERC'),
        //     (459, 'NORMANDY ENTERPRISES'),
        //     (460, 'NORTH PARK NOODLE HOUSE, INC.'),
        //     (461, 'NUTRITIVE SNACK FOOD CORPORATION'),
        //     (462, 'AMADO ONG/ O.C. GROCERY'),
        //     (463, 'OC VENTURES CORPORATION'),
        //     (464, 'OLEO-FATS INCORPORATED'),
        //     (465, 'PABLIFORD COMMERCIAL'),
        //     (466, 'PAN DE MANILA FOOD CO INC.'),
        //     (467, 'PANNI CARLO FRENCH BREADS AND PASTRIE'),
        //     (468, 'PANPLAZA BAKERY AND GROCERY'),
        //     (469, 'PAO YING FOOD, INC,'),
        //     (470, 'PEPSI COLA FAR EAST TRADE DEV CO'),
        //     (471, 'PINES'),
        //     (472, 'PINNACLE'),
        //     (473, 'POLLYN GROCERY'),
        //     (474, 'PRINCESS KIELLE ENTERPRISES'),
        //     (475, 'PURATOS (PHILS.) INC.'),
        //     (476, 'Q. PHILIPPINE PRODUCTS INT L.'),
        //     (477, 'R.G.L. FOOD PRODUCTS'),
        //     (478, 'RAMLEM GENERAL MERCHANDISE'),
        //     (479, 'RAMOS POULTRY SUPPLY'),
        //     (480, 'RBM GENERAL MERCHANDISE'),
        //     (481, 'REBANA FOOD PRODUCTS AND VEGETABLE'),
        //     (482, 'REPUBLIC BISCUIT CORPORATION'),
        //     (483, 'REPUBLIC BISCUIT CORPORATION (BUKID'),
        //     (484, 'RICHBAKE INC.'),
        //     (485, 'RICHLEY CORPORATION'),
        //     (486, 'RISING SUN COMMERCIAL CORPORATION'),
        //     (487, 'RITZ FOOD PRODUCT CORP.'),
        //     (488, 'RODILINA ENTERPRISES'),
        //     (489, 'ROLAN AND THESS GROCERY'),
        //     (490, 'RRDT ENTERPRISE'),
        //     (491, 'RUDY-BECCA COMENDADOR STORE'),
        //     (492, 'RUSIT BAKERY AND GROCERY STORE'),
        //     (493, 'SAN PABLO BAKERY AND ICE CREAM SUPPLY'),
        //     (494, 'SANTIAGO LUZON TRADING'),
        //     (495, 'SEVEN DRAGONS FOOD GALORE INC'),
        //     (496, 'SIR DINKS FOOD PRODUCTS, INC.'),
        //     (497, 'SNACKWELL FOODS CORPORATION'),
        //     (498, 'SOFIA BAKERY SUPPLY AND GEN. MDSE.'),
        //     (499, 'ST. THOMAS PAPER CORP.'),
        //     (500, 'STA. ROSA FARM PRODUCTS'),
        //     (501, 'STANBAKE MARKETING CORPORATION'),
        //     (502, 'STATELINE SNACK FOOD CORPORATION'),
        //     (503, 'SUCERE FOODS CORPORATION'),
        //     (504, 'SUN AND NELLY BAKERY SUPPLY'),
        //     (505, 'SUNCREST FOODS INCORPORATED'),
        //     (506, 'SUPER DOUGH FOOD AND CATERING CORP.'),
        //     (507, 'TA AND TO GENERAL MERCHANDISE'),
        //     (508, 'TABACO LA SUERTE CORPORATION'),
        //     (509, 'TARLAC L-7 TRADING'),
        //     (510, 'TAYTAY BAKERY'),
        //     (511, 'TEAMBAKE MARKETING CORPORATION'),
        //     (512, 'TED OLDTIMER LAPAZ BATCHOY'),
        //     (513, 'TEDDY AND EDITH GENERAL MERCHANDISE'),
        //     (514, 'THE FRESH BAKER MARKETING, INC.'),
        //     (515, 'THE REAL AMERICAN DOUGHNUT COMPANY,'),
        //     (516, 'TIPID MINI-MART'),
        //     (517, 'TITA ELY FOOD SHOP INC.'),
        //     (518, 'TOWIN ENTERPRISES'),
        //     (519, 'TUGUEGARAO NEW GOOD LUCK BAKERY PRO'),
        //     (520, 'UNCLE GEORGE BAKE-OFF'),
        //     (521, 'VELMAR GEN. MERCHANDISE'),
        //     (522, 'VILLAGE GOURMET CO., INC.'),
        //     (523, 'VIRGINIA BAKERY'),
        //     (524, 'VIZCAYA SUNRISE FARM SUPPLY'),
        //     (525, 'WC ANA GROCERY'),
        //     (526, 'WELLMAN TONG MARKETING CORPORATION'),
        //     (527, 'WINDON GEN MDSG CORP.'),
        //     (528, 'WTV MARKETING'),
        //     (529, 'YAK SEN GENERAL MERCHANDISE'),
        //     (530, 'YAO LIN BAKERY SUPPLY'),
        //     (531, 'YAPSON TRADING'),
        //     (532, 'YULEFEST CORPORATION'),
        //     (533, 'ZEST-O CORPORATION (MLA ACCT)'),
        //     (534, 'ZMB TRUCKING SERVICES'),
        //     (535, 'LOLA LUZ COUNTRYSIDE BAKESHOP'),
        //     (536, 'MACROHON STORE'),
        //     (537, 'MELROSE BAKESHOP'),
        //     (538, 'NAT BOCARILLO'),
        //     (539, 'PANATO BREAD CO.'),
        //     (540, 'PANNY HOME BAKE PRODUCTS'),
        //     (541, 'RJAY PICK N ROLL BAKESHOP'),
        //     (542, 'ROGELIA MATONDO'),
        //     (543, 'RUBEN BAKESHOP'),
        //     (544, 'SR. SAN JOSE FRANCHISING CORP.'),
        //     (545, 'STOP OVER BAKESHOP'),
        //     (546, 'SUGAR LOAF BAKERY'),
        //     (547, 'VILLAGE BREAD BAKESHOP'),
        //     (548, 'CRUZ, BERT'),
        //     (549, 'CHIONG STORE'),
        //     (550, 'DODONG BAKESHOP'),
        //     (551, 'CAMAY, ED'),
        //     (552, 'GLEN AGRIVET'),
        //     (553, 'GLEN STORE'),
        //     (554, 'JAY BAKESHOP'),
        //     (555, 'SUAREZ, JOJO'),
        //     (556, 'LABRADOR, JOSE'),
        //     (557, 'SANCHEZ, JUDY'),
        //     (558, 'JULIET BRAVO'),
        //     (559, 'JY STORE'),
        //     (560, 'LT BAKESHOP'),
        //     (561, 'MAASIN BAKESHOP'),
        //     (562, 'CANALES, MARILYN'),
        //     (563, 'MICHAEL ENT.'),
        //     (564, 'NIEVA STORE'),
        //     (565, 'PRIME COMMERCIAL'),
        //     (566, 'RAFAEL BAKESHOP'),
        //     (567, 'OCAMPO, RAUL'),
        //     (568, 'RAUL STORE'),
        //     (569, 'RJ BAKESHOP'),
        //     (570, 'RT BAKESHOP'),
        //     (571, 'INTEGRATED AQUACULTURE SPECIALIST,'),
        //     (572, 'JDA ENTERPRISE'),
        //     (573, 'JAV MARKETING'),
        //     (574, 'JERYL MARIE ENTERPRISE'),
        //     (575, 'ELGEE TRADERS'),
        //     (576, 'MONDE DENMARK NISSIN BISCUIT'),
        //     (577, 'PR TRADING AND GEN. SERVICE CO.'),
        //     (578, 'BUO, ELLA'),
        //     (579, 'SARMIENTO, EPHIL'),
        //     (580, 'RODRIGUEZ,ERWIN'),
        //     (581, 'UY, JOHN ALEXANDER'),
        //     (582, 'GUSTILO, JOSELITA'),
        //     (583, 'PEÑALOSA, ROSALIE'),
        //     (584, 'GUSTILO, RUEL'),
        //     (585, 'MENDOZA, LOUIE'),
        //     (586, 'LIAN HING TRADING'),
        //     (587, 'TIM ENTERPRISES'),
        //     (588, 'GECKO ENTERPRISE'),
        //     (589, 'JCT WHEAT AND SUGAR PRODUCTS'),
        //     (590, 'ROSE CHIN MARKETING'),
        //     (591, 'LU, SHEILA GRACE'),
        //     (592, 'MARANAN, PHILIP JUDE'),
        //     (593, 'MARANAN, RUTH MAE'),
        //     (594, 'PANADERO BAKESHOP-GEN. SAN'),
        //     (595, 'PANADERO BAKESHOP-SURIGAO'),
        //     (596, 'PANADERO BAKESHOP CORP.-DAVAO'),
        //     (597, 'DAVAO BAKERS CHOICE'),
        //     (598, 'FRESH N FAMOUS FOODS INC. - CHOWKI'),
        //     (599, 'DIPOLOG COMBINED COMMODITIES'),
        //     (600, 'TRADERS SUPERSTORE'),
        //     (601, 'YAN YAN COMMERCIAL'),
        //     (602, 'TCK FOOD PRODUCTS'),
        //     (603, 'JOENA PLASTIC AND GENERAL MERCHANDISE'),
        //     (604, 'ANDREW GROCERY'),
        //     (605, 'BAISA BAKERY AND GEN. MERCHANDISING'),
        //     (606, 'BONA BAKERY'),
        //     (607, 'LTS SUPERMARKET, INC.'),
        //     (608, 'GOLAND GROCERY'),
        //     (609, 'TONIES MART'),
        //     (610, 'TOPPERS MERCHANTILE'),
        //     (611, 'SAN ROQUE'),
        //     (612, 'TERO MARKETING'),
        //     (613, 'TESSIE ALONZO'),
        //     (614, 'ZENAIDA CABRAL'),
        //     (615, 'MA. ELEANOR BUCOY'),
        //     (616, 'MA. GRACIA CORTEZ'),
        //     (617, 'TUMADA, NENITA'),
        //     (618, 'DANGO, SAMUEL'),
        //     (619, 'OZAMIZ PROGRESSIVE'),
        //     (620, 'VISCAYNO, AILEEN MAY'),
        //     (621, 'ARSENIA STORE'),
        //     (622, 'ATHENA STORE'),
        //     (623, 'AYESA ROSE STORE'),
        //     (624, 'CARMELITA  CABALUNA'),
        //     (625, 'CAROLINA ENTERPRISE'),
        //     (626, 'DYNAMIC STAR MART'),
        //     (627, 'LEAH VASQUEZ STORE'),
        //     (628, 'ARACILLO, LUCENA'),
        //     (629, 'PAQUIT, RIO MIRANDA'),
        //     (630, 'SATURNINA STORE'),
        //     (631, 'TERESITA STORE'),
        //     (632, 'NICAN ENTERPRISE'),
        //     (633, 'ALESON TRADING'),
        //     (634, 'CHIONG, ANGEL'),
        //     (635, 'BALIWAG BAKERY'),
        //     (636, 'BERNARDO BROS'),
        //     (637, 'VS MARKETING'),
        //     (638, 'DLK MARKETING'),
        //     (639, 'GEORGE BAKERY'),
        //     (640, 'MULTIRICH FOOD CORPORATION- CAGAYAN'),
        //     (641, 'SANKEM TRADING'),
        //     (642, 'TCL CORPORATION'),
        //     (643, 'Z. ZGLA TRADING CORPORATION'),
        //     (644, 'LKS CONVENIENT STORE'),
        //     (645, 'NEW ORIENTAL TRADING'),
        //     (646, 'NEW TAN SENG'),
        //     (647, 'TAKE N PAY'),
        //     (648, 'VINACE ENTERPRISE'),
        //     (649, 'ZAMBOANGA GRAIN MART'),
        //     (650, 'GOLDEN GRAINS MART'),
        //     (651, 'ZC UNITED PHARMACY'),
        //     (652, 'ACLAO STORE'),
        //     (653, 'AMON-R8 COMMERCIAL, INC.'),
        //     (654, 'BRUTAS STORE'),
        //     (655, 'GRACE BENDICION'),
        //     (656, 'ILUMINADA MARKETING'),
        //     (657, 'DY, LOMING'),
        //     (658, 'PIAMONTE STORE'),
        //     (659, 'ROBERT VILLAMOR'),
        //     (660, 'RONCALES STORE'),
        //     (661, 'SHOPPER BUDGET'),
        //     (662, 'YAKMAN BENDICION'),
        //     (663, 'YAP BAKERY'),
        //     (664, 'TACLOBAN CANETE ENTERPRISE'),
        //     (665, 'BG FOODS CORPORATION'),
        //     (666, 'GRACE CONCHA'),
        //     (667, 'JG FOODS CORPORATION'),
        //     (668, 'LEUTERIO STORE'),
        //     (669, 'RISING SUN FOOD CORP.'),
        //     (670, 'SIETE MARIAS BAKERY AND GROCERY'),
        //     (671, 'ACOSTA, ELMER'),
        //     (672, 'AHHI, JOHN'),
        //     (673, 'AIM VALUE VENTURES'),
        //     (674, 'AKLAN SHOPPERS MART'),
        //     (675, 'AKLAN VISAYAN'),
        //     (676, 'ALADINO BAKESHOP'),
        //     (677, 'AMAGIN, JOSEPH'),
        //     (678, 'AMAR, REMY'),
        //     (679, 'AMIGO TERRACE HOTEL'),
        //     (680, 'ANGELINA BAKESHOP'),
        //     (681, 'NEW ILOILO ASIATIC TRADING'),
        //     (682, 'ASTER ENTERPRISE'),
        //     (683, 'ANDICOY, GINA'),
        //     (684, 'AYCO, CHERIDAN'),
        //     (685, 'AYCO, MACEL'),
        //     (686, 'AYING, JOSEPH'),
        //     (687, 'B AND R CASH STORE'),
        //     (688, 'BABY BAKERY'),
        //     (689, 'BABY BOY MINI MART'),
        //     (690, 'BAKER LAND'),
        //     (691, 'BALTAZAR, ROMEO'),
        //     (692, 'BANGA COUNTRY BAKESHOP AND GROCERY'),
        //     (693, 'BARCILLO, NENA'),
        //     (694, 'BAYATE BAKERY'),
        //     (695, 'BESA, GEMMA'),
        //     (696, 'BG COMMERCIAL'),
        //     (697, 'BISCOCHO HAUS'),
        //     (698, 'JOCELYN BOLUSO'),
        //     (699, 'BREADWAY'),
        //     (700, 'BUHO BAKERY, INC.'),
        //     (701, 'VICENTE BUNDA'),
        //     (702, 'BURGOS BAKERY'),
        //     (703, 'BUYCO, LUCIO'),
        //     (704, 'CAKE HOUSE'),
        //     (705, 'CAKE ETC'),
        //     (706, 'CARMELITE SISTER'),
        //     (707, 'CITIZEN BAZAR'),
        //     (708, 'CITY SQUARE'),
        //     (709, 'CPT MART'),
        //     (710, 'DAILY BUNS'),
        //     (711, 'DAILY FOODS'),
        //     (712, 'DD FOODS INC.'),
        //     (713, 'DEAN BAKESHOP'),
        //     (714, 'ERIC DELFIN'),
        //     (715, 'DELIFRANZ BAKESHOP'),
        //     (716, 'DIOLA, LESLIE'),
        //     (717, 'DIONELA, DANILO'),
        //     (718, 'GENERALATE HOUSE'),
        //     (719, 'JINKY DOLOR'),
        //     (720, 'DOMINGO, EVA'),
        //     (721, 'DON DON BAKESHOP'),
        //     (722, 'DORINE J-BREAD ENTERPRISES'),
        //     (723, 'DY, ESTELITA'),
        //     (724, 'DY, FRANCINE'),
        //     (725, 'EBALLES, ALFRED'),
        //     (726, 'ECO, ERNESTO'),
        //     (727, 'ELAURIA, JOSEPHINE'),
        //     (728, 'ELEONOR SY'),
        //     (729, 'BTJ MARKETING'),
        //     (730, 'EMOLAGA, ARCHIE'),
        //     (731, 'ESLABAN, MANUELA'),
        //     (732, 'ESPELITA, ANDREW'),
        //     (733, 'ESTANCIA SUPERMART'),
        //     (734, 'ESTIPONA, ANTON'),
        //     (735, 'EVANGELISTA, DANILO'),
        //     (736, 'EVERGREEN WHEAT N OATS BAKESHOP'),
        //     (737, 'NORMA FAELDONIA'),
        //     (738, 'FANCOM'),
        //     (739, 'FIL BAKE FOOD CORPORATION'),
        //     (740, 'AKLAN FILIPINO BAKERY'),
        //     (741, 'GOLDEN PAVILLION FOOD SALES CORPORA'),
        //     (742, 'GALLEGA, ROGER'),
        //     (743, 'GAMBOA, LEONARDO'),
        //     (744, 'GAMUSA, ISIDRO'),
        //     (745, 'GANEA, JOCELYN'),
        //     (746, 'GATILOGO, DEBRA'),
        //     (747, 'GEONANGA, BONIFACIO'),
        //     (748, 'GILBERT COMM .'),
        //     (749, 'GLORIA GAMARCHA'),
        //     (750, 'GO, FRINITA'),
        //     (751, 'GOLDEN DELTA'),
        //     (752, 'THE GRAIN BAKER SPECIALTY STORE'),
        //     (753, 'ILOILO GRAND HOTEL'),
        //     (754, 'GUMAREN, LYDIA'),
        //     (755, 'HARVEST WHEAT BAKED FOODS, INC.'),
        //     (756, 'HATCH FOOD PRODUCTS, INC.'),
        //     (757, 'HATZHERZ MARKETING'),
        //     (758, 'HENANN HOTEL MANAGEMENT INC.'),
        //     (759, 'HO, FLORES LARA'),
        //     (760, 'HONDRADE STORE'),
        //     (761, 'ILOILO SUPERMART INC.'),
        //     (762, 'IMPERIAL GROCERY'),
        //     (763, 'ILOILO NATIONAL HARDWARE'),
        //     (764, 'INJAP SUPERMART'),
        //     (765, 'JAMANDRE, VITA'),
        //     (766, 'JARA FOODS INC.'),
        //     (767, 'JMB TRADERS'),
        //     (768, 'JPS SMARTBIZ ENTERPRISE'),
        //     (769, 'JSP MINIMART'),
        //     (770, 'JULIE BAKESHOP'),
        //     (771, 'KALIBO DAINTY BAKERY AND GROCERY'),
        //     (772, 'KFH'),
        //     (773, 'KH SHOPPING CENTER'),
        //     (774, 'KIM HUATCOMMERCIAL'),
        //     (775, 'KING DELIGHT'),
        //     (776, 'KONGKEE RESTAURANT'),
        //     (777, 'LA COMPANIA DE LECHE INC.'),
        //     (778, 'LA FUERZA BAKESHOP AND GROCERY'),
        //     (779, 'LAUREA, CARLOS'),
        //     (780, 'LAURON, LUIS'),
        //     (781, 'LEDI SUPERMART'),
        //     (782, 'LEE, NESTOR'),
        //     (783, 'LIM SI TRADING'),
        //     (784, 'LOLA MADGES BAKESHOP'),
        //     (785, 'LOPEZ, LORY BELLE'),
        //     (786, 'LOS FILIPINOS BAKERY'),
        //     (787, 'LOVE STORE'),
        //     (788, 'LYB STORE'),
        //     (789, 'LOREFE BAKESHOP'),
        //     (790, 'MABINI, TEOFILO'),
        //     (791, 'MABUNAY, ELIZABETH'),
        //     (792, 'MACABENTA, DELIA'),
        //     (793, 'MADRID, ROSEMARIE'),
        //     (794, 'MAGBANUA, PETE'),
        //     (795, 'MANOLETTE BAKESHOP - PANAY'),
        //     (796, 'MIJARES, DONATO'),
        //     (797, 'MILAGROSA J SHIPPING CORP.'),
        //     (798, 'MMC BREADSHOP'),
        //     (799, 'MOJAS, MONENA'),
        //     (800, 'MOLO COUNTRY BAKESHOP'),
        //     (801, 'MOTO FOODS'),
        //     (802, 'NAN YUN LAN'),
        //     (803, 'NANIT, CRESENCIA'),
        //     (804, 'WENCESLAO NAVARRA'),
        //     (805, 'NAVARRO, TRICELLE'),
        //     (806, 'NEW ARTURO MARKETING'),
        //     (807, 'NEW PAVIA MEKE FACTORY'),
        //     (808, 'NOBLE, REBECCA'),
        //     (809, 'ONG, ADELENE JOIE'),
        //     (810, 'ONG, LEONCIO'),
        //     (811, 'ONG, YOLANDA'),
        //     (812, 'ONGLATCO, PETER'),
        //     (813, 'PANADERIA NI PA-A'),
        //     (814, 'PALACIOS, LORRY'),
        //     (815, 'PALMARES, LORENZO'),
        //     (816, 'PANADERIA DE ILOILO'),
        //     (817, 'MARKET PLACE CAFE AND BAKESHOP'),
        //     (818, 'PEMPOT SUPER GRINDER'),
        //     (819, 'PEREZ, PERLITA'),
        //     (820, 'PHILIPPINE FOREMOST MILLING CORPORA'),
        //     (821, 'PONCIANO RESTAURANT'),
        //     (822, 'PORRAS, RODRIGO'),
        //     (823, 'PRINCE DELI BREAD'),
        //     (824, 'PRUDENTE, LEONARD'),
        //     (825, 'QUEEN DELI BREAD'),
        //     (826, 'R AND C SUPERMART INC.'),
        //     (827, 'RENEWAL HOUSE'),
        //     (828, 'ROBERTO HOUSE'),
        //     (829, 'ROGER TRADING'),
        //     (830, 'ROHI MARKETING'),
        //     (831, 'ROSALINA LAMPARERO'),
        //     (832, 'ROYAL GROCERY'),
        //     (833, 'SALNOR BAKESHOP'),
        //     (834, 'SALVADOR, GLORIA'),
        //     (835, 'SANTOS, LORENZO'),
        //     (836, 'SANTOS, MELODY'),
        //     (837, 'SARI-SARI BREAD NETWORK INT . CORP'),
        //     (838, 'SB VARIETY'),
        //     (839, 'SEGRE, MAR'),
        //     (840, 'SINGH, JOHN'),
        //     (841, 'SINGH, KULWINDER'),
        //     (842, 'SINGH, NARENDER'),
        //     (843, 'SISON, JENIL'),
        //     (844, 'SOLIS, MARBIE'),
        //     (845, 'SOUTHERN TRADING'),
        //     (846, 'SNC POULTRY SUPPLY'),
        //     (847, 'SOCORRO TAKE HOME'),
        //     (848, 'ST PAUL MARKETING INC.'),
        //     (849, 'SULPICIO LINES, INCORPORATED'),
        //     (850, 'SUMMA FOODS CORPORATION'),
        //     (851, 'SUNMAR MEKE FACTORY'),
        //     (852, 'SUPER BAKER, INC.'),
        //     (853, 'TAN, EDNA'),
        //     (854, 'GILBERT TAN'),
        //     (855, 'TAN, MICHAEL'),
        //     (856, 'TED OLD TIMER LAPAZ BATCHOY'),
        //     (857, 'TFA STORE'),
        //     (858, 'THERESA BAKESHOP'),
        //     (859, 'TIBIAO BAKERY'),
        //     (860, 'TIONG SHING GROCERY AND MEKE'),
        //     (861, 'OUR LADY OF THE TRAPPIST'),
        //     (862, 'TRI B MARKETING'),
        //     (863, 'JOCELYN TRINO'),
        //     (864, 'TRIX PIZZA MIA'),
        //     (865, 'UFO COMMERCIAL'),
        //     (866, 'UNGKA MEKE'),
        //     (867, 'VALENCIA, ROLAND'),
        //     (868, 'VALENZUELA, ROBERTO'),
        //     (869, 'VARIOUS-AR-PDC BEGINNING BAL.'),
        //     (870, 'VELFRAM  FOODS CORP.'),
        //     (871, 'VILLANUEVA, JESSICA'),
        //     (872, 'VILLANUEVA, JULIET'),
        //     (873, 'ILOILO WASHINGTON COMMERCIAL, INC.'),
        //     (874, 'WASHINGTON COMMERCIAL, INC.'),
        //     (875, 'CENTER POINT PLASTIC'),
        //     (876, 'WVA HEALTH FOODS'),
        //     (877, 'RISE AND SHINE'),
        //     (878, 'GO, REY'),
        //     (879, 'BAYA, DONNA'),
        //     (880, 'BERNADITH SARNO'),
        //     (881, 'CELSO DARUNDAY'),
        //     (882, 'EVANGELINE CARAECLE'),
        //     (883, 'FELICITAS DELA CRUZ'),
        //     (884, 'GINAFLOR ROTA'),
        //     (885, 'JULIE ATILANO'),
        //     (886, 'YAOKASIN TRADING'),
        //     (887, 'ALMA BAKESHOP'),
        //     (888, 'ELKE BREADHAUS'),
        //     (889, 'HONEY AND DAVE'),
        //     (890, 'YU, JIMMY'),
        //     (891, 'KENNETH BAKESHOP'),
        //     (892, 'QUALITY BREAD'),
        //     (893, 'JOSE MANA-OG'),
        //     (894, 'ARMANDO FABILA'),
        //     (895, 'GEORGE SALAS'),
        //     (896, 'HELEN TOLENTINO'),
        //     (897, 'JANET QUIMBO'),
        //     (898, 'LENY CINCO'),
        //     (899, 'MARIANO GARCIA'),
        //     (900, 'MARIO ESMANDE'),
        //     (901, 'MIKE MARAGRAG'),
        //     (902, 'CUYOS, MOLI'),
        //     (903, 'ORTI, RAMIL'),
        //     (904, 'RENE DE LA TORRE'),
        //     (905, 'RIC ORTEGA'),
        //     (906, 'RICHARD  ORTI'),
        //     (907, 'RICO ESPLANADA'),
        //     (908, 'ALCAZAREN, MARIBERT'),
        //     (909, 'BLUE HILLS MARKETING'),
        //     (910, 'MANDAUE PACIFIC INT . TRADING'),
        //     (911, 'NEW HOPE COMMERCIAL'),
        //     (912, 'SANDRO MARKETING'),
        //     (913, 'DENTRADE ENTERPRISES'),
        //     (914, 'CANDL COMM .'),
        //     (915, 'ALL FRESH FOOD PRODUCTS, INC.'),
        //     (916, 'CC COMMERCIAL'),
        //     (917, 'FOODMAN INDUSTRIES CORP.'),
        //     (918, 'GEM BAKESHOP'),
        //     (919, 'IC MART'),
        //     (920, 'GLOBAL FOODS DISTRIBUTION'),
        //     (921, 'GREAT CROWN DISTRIBUTION, INC'),
        //     (922, 'JOELING STORE'),
        //     (923, 'LAO SIAN COMMERCIAL'),
        //     (924, 'LIT-LIT STORE'),
        //     (925, 'MELVAS GROCERY'),
        //     (926, 'NEW WM BAKESHOP'),
        //     (927, 'ORION STORE'),
        //     (928, 'PADILLA STORE'),
        //     (929, 'PEARL ORIENT TRADING CORP.'),
        //     (930, 'POLDING STORE'),
        //     (931, 'RJ BOY STORE'),
        //     (932, 'ROBINHOOD MANUFACTURING'),
        //     (933, 'SKZ 777 TRADING'),
        //     (934, 'GEPAYA STORE'),
        //     (935, 'ARBEES BAKESHOP'),
        //     (936, 'BAKE N SAVE'),
        //     (937, 'BREAD EXPRESS-CONSOLACION'),
        //     (938, 'BREAD EXPRESS-MAGUIKAY'),
        //     (939, 'BREAD EXPRESS-MANDAUE'),
        //     (940, 'DOUBLE A BAKERY'),
        //     (941, 'EASTERN MKTG.'),
        //     (942, 'EY ENTERPRISE'),
        //     (943, 'FLOUR AND BUTTER BAKESHOP'),
        //     (944, 'GABISAN STORE'),
        //     (945, 'GAL BAKERY'),
        //     (946, 'JECZEL MINIMART'),
        //     (947, 'JL DIAMOND STAR INCOPORATED'),
        //     (948, 'KISHA BAKESHOP'),
        //     (949, 'LEONARD BAKESHOP'),
        //     (950, 'LEYTE BAKERS'),
        //     (951, 'BACOLOD LA FILIPINA TRADING CORPORA'),
        //     (952, 'NEGROS FOOD SUPPLY'),
        //     (953, 'NORTHERN TRDG.'),
        //     (954, 'OSCAR BAKESHOP'),
        //     (955, 'PANADERO BAKESHOP'),
        //     (956, 'PARK AND GO-CAMIGUIN'),
        //     (957, 'PARK AND GO-CANDUMAN'),
        //     (958, 'PARK AND GO-CATAINGAN'),
        //     (959, 'PARK AND GO-MASBATE'),
        //     (960, 'SOUTH SEA COMMERCIAL'),
        //     (961, 'SWAN REFRESHMENT'),
        //     (962, 'YULEFEST CAGAYAN DE ORO'),
        //     (963, 'EWG TRANSPORT'),
        //     (964, 'FERNA CORPORATION'),
        //     (965, 'BISCONFOOD INTERNATIONAL, INC.'),
        //     (966, 'JOCKER FOODS INDUSTRIES'),
        //     (967, 'AGRIPLUS CENTER COMPANY'),
        //     (968, 'REGAL INT  SNACK FOOD CORP.'),
        //     (969, 'NU FOOD CORPORATION'),
        //     (970, 'ABOITIZ TRANSPORT SYSTEM'),
        //     (971, 'AMSTAR CORPORATION'),
        //     (972, 'ANG CHIN HUA'),
        //     (973, 'BENJAMIN YUSOP'),
        //     (974, 'AHMAD YASIM'),
        //     (975, 'FARMERS ENTERPRISE'),
        //     (976, 'FLORO VERTULFO'),
        //     (977, 'GLENN AHHI'),
        //     (978, 'JOHANNA MARKETING'),
        //     (979, 'JYSMI SUPERMART'),
        //     (980, 'MAXIMO TRADERS'),
        //     (981, 'NEW CENTRAL GROCERY'),
        //     (982, 'RD MARKETING'),
        //     (983, 'RODCAR GEN. MERCHANDISE'),
        //     (984, 'SMC ENTERPRISE'),
        //     (985, 'UP AND COMING DISTRIBUTION'),
        //     (986, 'VALENCIA SUPERSALES'),
        //     (987, 'VLADEMER BAKESHOP'),
        //     (988, 'NEGROS NAVIGATION CO., INC.'),
        //     (989, 'ALIMORONG, ARNOLD'),
        //     (990, 'COMPLETE LOGISTIC CONTROL INC.'),
        //     (991, 'DADZVILLE TRADING AND MARKETING ENT'),
        //     (992, 'PB CO PEANUT BUTTER COMPANY FOOD IN'),
        //     (993, 'REGENT FOODS CORP.'),
        //     (994, 'TITAN-ASIA LOGISTICS'),
        //     (995, 'FRANK GEN. MERCHANDISE'),
        //     (996, 'ROMMEL YNION'),
        //     (997, 'UNISUN FOOD PRODUCTS'),
        //     (998, 'TRANS ASIA SHIPPING'),
        //     (999, 'TJN PASALUBONG FOODS, INC.'),
        //     (1000, 'PHIL.LEADING INFINITE LOGISTICS,INC'); 
            
        //     SET IDENTITY_INSERT companies OFF;
        // ");

        //  $this->command->info('Users table seeded');

         // batch 2 
          DB::statement("
            SET IDENTITY_INSERT companies ON;
            INSERT companies(id, name)
            VALUES(1001, 'GOLDEN FINN AND JOSEPH INCORPORATED'),
            (1002, 'ONE TIME CUSTOMER'),
            (1003, 'NORTHPOINT BAKERY AND GEN. MDSE.'),
            (1004, 'SOROSORO IBABA DEV. COOP.'),
            (1005, 'HKK GOLD MARKETING'),
            (1006, 'MATEY GENERAL MERCHANDISE'),
            (1007, 'LTS CITIFOODS'),
            (1008, 'LTS SUPERMARKETS, INC.'),
            (1009, 'MAE-SAN QUALITY BAKERY CORP.'),
            (1010, 'J GEM R BAKERY AND FOOD PRODUCTS'),
            (1011, 'COKALIONG SHIPPING LINES'),
            (1012, 'SHEEN-SHEEN TRUCKING SERVICES'),
            (1013, 'JULIES FRANCHISE CORPORATION'),
            (1014, 'CHOCOVRON GLOBAL CORP.'),
            (1015, 'ARMANDO TRINIDAD'),
            (1016, 'MARILYN TICAR'),
            (1017, 'TEODOR AMOR'),
            (1018, 'HONAI FOODS CORPORATION'),
            (1019, 'AMELIA FURATERO'),
            (1020, 'ANTHONY TRINIDAD'),
            (1021, 'CHRISTINE DEE'),
            (1022, 'EDWARD SANTOS'),
            (1023, 'ILDEFONSO LANDOY'),
            (1024, 'INDAY STORE'),
            (1025, 'JANINE FERNANDEZ'),
            (1026, 'JANA GONZALES'),
            (1027, 'J J STORE'),
            (1028, 'JOCELYN VILLARUEL'),
            (1029, 'JOHN SEGOVIA'),
            (1030, 'JOSEPHINE CHUA'),
            (1031, 'RAMON GO'),
            (1032, 'NOEL PARREŇO'),
            (1033, 'RODNEY PINEDA'),
            (1034, 'ROSARIO GOLEZ'),
            (1035, 'SUMAGAYSAY STORE'),
            (1036, 'STAR COMMERCIAL'),
            (1037, 'WILLIE SALAZAR'),
            (1038, 'VIRGO TRADING'),
            (1039, 'CARLOS CABALLERO'),
            (1040, 'ANTONIO BERNALES'),
            (1041, 'CESAR SALES'),
            (1042, 'CEFERINO GAMIL'),
            (1043, 'EDNA MARTINES'),
            (1044, 'MANUEL SANTOS'),
            (1045, 'FIDEL LAPASTARAN'),
            (1046, 'RODEL MACAHILIG'),
            (1047, 'RAMON CASTILLANES'),
            (1048, 'VIRGINIA MALONES'),
            (1049, 'ANDY ALBA'),
            (1050, 'HENRY LACSON'),
            (1051, 'ARNEL ENCARNACION'),
            (1052, 'JONALYN ROJO'),
            (1053, 'MAILEEN DE GUZMAN'),
            (1054, 'LANETTE DE LOS SANTOS'),
            (1055, 'MARICAR ALMANON'),
            (1056, 'MARIANITO CADORNIGARA'),
            (1057, 'MARK ORIBE'),
            (1058, 'THERESA TRESPECES'),
            (1059, 'JAYME NUMERIANO JR.'),
            (1060, 'NORMA LUZONG'),
            (1061, 'ANALYN CASTILLER'),
            (1062, 'JERRY VELEZ'),
            (1063, 'ROGER GUPETIO'),
            (1064, 'ARNULFO CABANGIL'),
            (1065, 'DENZEL CALAMBRO JR.'),
            (1066, 'BREA CORINNE DAPAT'),
            (1067, 'SIMONETTE RENZO'),
            (1068, 'RANDY DAMAYO'),
            (1069, 'RENEE SALINDOG'),
            (1070, 'MA. DIORELLA JIMENA'),
            (1071, 'JOEY JANINA'),
            (1072, 'MINETTE SELINDA'),
            (1073, 'CRISPIN TAPAN'),
            (1074, 'BASILIO SULTAN'),
            (1075, 'SUN FLOWER BAKER PRODUCTS, INC.'),
            (1076, 'RODELIO A. TENORIO'),
            (1077, 'FAST CARGO'),
            (1078, 'ROLLY TORRE'),
            (1079, 'NEWTON FOOD PRODUCTS MFG. CO., INC.'),
            (1080, 'GOLD PRIZE FOOD MFG. CORP.'),
            (1081, 'DEL MONTE PHILIPPINES, INC.'),
            (1082, 'D GALAXY PHILS. INT . TRDG. CORP.'),
            (1083, 'LUCIA MATULAC'),
            (1084, 'ARTEMIO TOBRILLO'),
            (1085, 'BRANDO BRITANICO'),
            (1086, 'MARIVIC LUTERO'),
            (1087, 'LUCIA SOLAS'),
            (1088, 'ASUCENA MONTEALTO'),
            (1089, 'JASELFA LIM'),
            (1090, 'LUIS BERMIJO'),
            (1091, 'WILFREDO SIA'),
            (1092, 'MARIO LOCSIN'),
            (1093, 'CESAR CAMARIG'),
            (1094, 'JESUS ALCUBA'),
            (1095, 'JOSE NATIVIDAD'),
            (1096, 'EDNA ARANETA'),
            (1097, 'MYRNA PALACIOS'),
            (1098, 'JOE KUAN FOOD CORP.'),
            (1099, 'LA ROSE NOIRE PHILIPPINES, INC.'),
            (1100, 'DELICIOUS BAKERY'),
            (1101, 'JENWARD LIM KO'),
            (1102, 'DULGIES DESSERTS AND CAFE'),
            (1103, 'CENTERPOINT PLASTIC CENTER'),
            (1104, 'TRIPLE J MEKE FACTORY'),
            (1105, 'FILBAKE FOOD CORPORATION'),
            (1106, 'DRB DISTRIBUTION'),
            (1107, 'MANNA SHABBAT CORP.'),
            (1108, 'MARIBERT CORPORATION'),
            (1109, 'NEWLY WEDS FOODS (PHILIPPINES)'),
            (1110, 'TACLOBAN GOODWILL COMMERCIAL'),
            (1111, 'NEW LIAN HING TRADING'),
            (1112, 'CATBALOGAN SAN ROQUE MARKETING'),
            (1113, 'GOSONS FOOD CORPORATION'),
            (1114, 'MARINELLA TRUCKING SERVICES'),
            (1115, 'PREMIUM PLYWOOD MANUFACTURING CORP'),
            (1116, 'UNCLE GEORGE BREADS AND PASTRIES INC.'),
            (1117, 'SEAWIDE MARINE SERVICES'),
            (1118, 'MAMA TINA PASTA COMPANY, INC.'),
            (1119, 'GHERMEL MARKETING'),
            (1120, 'MB STORE'),
            (1121, 'DELRIC ENTERPRISES'),
            (1122, 'OCEANIC CONTAINER LINES, INC.'),
            (1123, 'PTO TONIES MART'),
            (1124, 'CASILDA BAKESHOP'),
            (1125, 'JESE BAKESHOP'),
            (1126, 'E AND B FOOD SELECTION INC.'),
            (1127, 'SEEBRA FOODS INC.'),
            (1128, 'ERGEN, DIANA J.'),
            (1129, 'DE LEON, MARK JOSEPH'),
            (1130, 'BODEGA SITE I.T. SOLUTIONS, INC.'),
            (1131, 'GOLDEN SHARKSFIN VENTURES, INC.'),
            (1132, 'AMIGO SHIPPING CORPORATION'),
            (1133, 'Z.C. INTEGRATED PORT SERVICES, INC.'),
            (1134, 'DURONG MALUNGGAY PANDESAL'),
            (1135, 'CASTRO, ROMEO S.'),
            (1136, 'DWINDON GENERAL MERCHANDISE'),
            (1137, 'E.J. AQUINO CRUZ TRADING'),
            (1138, 'JVS SUPERMART'),
            (1139, 'EMONG MALUNGGAY PANDESAL'),
            (1140, 'FLORES, RALPH VINCENT SY'),
            (1141, 'GOLD MEDAL FOOD MFG. CORP.'),
            (1142, 'SY, JONATHAN'),
            (1143, 'MONZON GENERAL MERCHANDISE'),
            (1144, 'BUDONG MALUNGGAY PANDESAL'),
            (1145, 'QUEENS BEST COOKING OIL AND'),
            (1146, 'DENCHEL ENTERPRISE, INC.'),
            (1147, 'BLUE-BIRD RAPTOR AGRI-VET AND'),
            (1148, 'BEAUCHEM THERMTECH GROUP, INC.'),
            (1149, 'E.D. SALES CENTER'),
            (1150, 'VENEZIANO PIZZERIA'),
            (1151, 'CROWN PRIME ASIA CORPORATION'),
            (1152, 'HENANN RESORTS, INC.'),
            (1153, 'BAJ TRUCKING SERVICES'),
            (1154, 'PHILIPPINE SPAN ASIA, INC.'),
            (1155, '2012 TRADING AND GENERAL MDSE., INC.'),
            (1156, 'RAXA TRADING'),
            (1157, 'RHAYMAR ENTERPRISES'),
            (1158, 'YM CARGO TRANSPORT CORP.'),
            (1159, 'LE JOIE BAKESHOP'),
            (1160, 'DAGO, LEELYN COLGROVE'),
            (1161, 'JOYCE AND TRINING VARIETY STORE'),
            (1162, 'KCC PROPERTY HOLDING, INC.'),
            (1163, 'ALIMENTUM BASIC CORPORATION'),
            (1164, 'SECRET RECIPES FOOD CORP.'),
            (1165, 'NARITA SNACK FOOD CORPORATION'),
            (1166, 'SWEET BAUM FACTORY INC.'),
            (1167, 'SAKANDAL, FAIDAZIR'),
            (1168, 'YULEFEST CORPORATION-ILOILO'),
            (1169, 'NAVARRO, ERIC'),
            (1170, 'LORENZO SHIPPING CORP.'),
            (1171, 'CGE BAKESHOP'),
            (1172, 'ST. PAUL HOSPITAL OF ILOILO, INC.'),
            (1173, 'ALTURAS SUPERMARKET'),
            (1174, 'YAOKASIN TRADING-MLA'),
            (1175, 'DENT TRADE ENTERPRISES'),
            (1176, 'YEAR LUCK FOOD AND INDUSTRIAL CORP.'),
            (1177, 'PAN DE MANILA FOOD CO INC.-ILOILO'),
            (1178, 'OEUF D OR INC.'),
            (1179, 'SWEETMAKER CORPORATION'),
            (1180, 'HEALTH IS WEALTH ENTERPRISE'),
            (1181, 'JOSIE D. PILAPIL BAKERY SUPPLIES'),
            (1182, 'PORT BAKER COMMODITIES'),
            (1183, 'TURRIS PHIL. INC.'),
            (1184, 'KIMKEL TRADING'),
            (1185, 'Micro-Health Trading, Inc.'),
            (1186, 'Sterling Direct Sales Network, Inc.'),
            (1187, 'WHEAT CITY INTERNATIONAL FOOD CORP.'),
            (1188, 'ILOILO GRAIN COMPLEX CORPORATION'),
            (1189, 'NUEVA VIZCAYA RISING SONS MULTI-PUR'),
            (1190, 'NEW STAR APA CORP.'),
            (1191, 'RECIPE FOOD MANUFACTURING'),
            (1192, 'ANG, DANILO G.'),
            (1193, 'AMORGANDA MINI MART'),
            (1194, 'TAMPUS, EDNA R.'),
            (1195, 'FELICISIMO MARTINEZ AND CO., INC.'),
            (1196, 'NICE AND WISE CONVENIENT STORE AND BAKE'),
            (1197, 'PAPAY BAKESHOP CORPORATION'),
            (1198, 'ILOILO LOS FILIPINOS BAKERY, INC.'),
            (1199, 'GOOD HEART FOOD AND INDUSTRIAL'),
            (1200, 'JNRM CORPORATION'),
            (1201, 'JULAND ENTERPRISES'),
            (1202, 'ENCINO FOOD LINKS'),
            (1203, 'BIG E FOOD CORPORATION'),
            (1204, '3ES LOGISTICS SERVICES'),
            (1205, 'Ponsica, Ronald Lobster Yap'),
            (1206, 'FASTCARGO LOGISTICS CORPORATION'),
            (1207, 'SENDOS EXPRESS CARGO FORWARDER'),
            (1208, 'COTS FREIGHT INTERNATIONAL INC.'),
            (1209, 'F. GUTIERREZ STORE'),
            (1210, 'VISA CARGO SERVICES CORP.'),
            (1211, 'MORETA SHIPPING LINES INC.'),
            (1212, 'GITA, MARIE ANTONETTE ASUNCION'),
            (1213, 'MAFLOR HOME OF HEALTHY FOOD'),
            (1214, 'ROSALIE S. TRENAS CORPORATION'),
            (1215, 'RCHG STORE'),
            (1216, 'SAGANA MART'),
            (1217, 'GABARRA STORE'),
            (1218, 'KET TRADING'),
            (1219, 'MANNTAN CORP.'),
            (1220, 'CRYSTAL HEARTS BAKERY'),
            (1221, 'JCGKI General Merchandise'),
            (1222, 'PRIME SOLID ENTERPRISE'),
            (1223, 'R.G.L. Bakery Supplies'),
            (1224, 'ROVEA GARAYGAY MEKE FACTORY'),
            (1225, 'IFMC NOODLES FACTORY CO., LTD.'),
            (1226, 'RADRAGON COMMERCIAL'),
            (1227, 'R AND Y BAKERY AND SARI-SARI STORE'),
            (1228, 'RLY STORE'),
            (1229, 'RBC Best Baker Foods Incorporated'),
            (1230, 'RBC First Baker Corporation'),
            (1231, 'KARLO DENNY PANCHO ILANO'),
            (1232, 'MDJJ Bakery Supply'),
            (1233, 'FIRST LAGUNA MARKETING COOPERATIVE'),
            (1234, 'IFP MANUFACTURING CORPORATION'),
            (1235, 'SY, ROBERTO'),
            (1236, 'GMRT TRADING'),
            (1237, 'GYOZA SPECIALIST INC. (OSAKA OHSHO)'),
            (1238, 'BRYANT MILLING AND MARKETING'),
            (1239, 'DPA MARKETING'),
            (1240, 'BMO STORE'),
            (1241, 'TEÑIDO, HANELYN JARO'),
            (1242, '3L RSJ TRUCKING SERVICES'),
            (1243, 'AL RAZON FOODS CORPORATION'),
            (1244, 'ADAMO AGRITURISMO, INC.- ORMOC'),
            (1245, 'ADAMO AGRITURISMO, INC.-TACLOBAN'),
            (1246, 'CO, DENNIS'),
            (1247, 'RHE BAKERY SUPPLIES AND GENERAL'),
            (1248, 'VIDAL COMMERCIAL CENTER INC.'),
            (1249, 'CITIMAX GROUP INC.'),
            (1250, 'ALDRIN FRED GENERAL MERCHANDISE'),
            (1251, 'DECINE VILLACORTA'),
            (1252, 'LEE BAKERY TUDELA, INC.'),
            (1253, 'LARRY-ALMA GEN. MERCHANDISE'),
            (1254, 'PANNY HOMEBAKE RPODUCTYS, INC.'),
            (1255, 'LGVR MULTI MOTOR SERVICE CENTER'),
            (1256, 'ONG, AMADO'),
            (1257, 'ROBIS, WILLARD MARIN'),
            (1258, 'CHEYENNE BAKERY SUPPLY'),
            (1259, 'DLA NATURALS, INC.'),
            (1260, 'ZDS BUFFALO INDUSTRIES, INC.'),
            (1261, 'BATANGUENO EL PANADERO INC.'),
            (1262, 'YODA BAKESHOP AND GENERAL'),
            (1263, 'GONZALES, MADONNA REYES'),
            (1264, 'MACAPAGAL, EINAR'),
            (1265, 'ODICTA, NOEL B.'),
            (1266, 'DUY STORE'),
            (1267, 'UNIVERSAL BRAND CONCEPTS AND'),
            (1268, 'NANAY VICIT SARI SARI STORE AND'),
            (1269, 'MFP HOME OF QUALITY FOOD CORP.'),
            (1270, 'SORIANO, ELEANOR ISIDRO'),
            (1271, 'CEPEDA FOOD MARKETING'),
            (1272, 'KALLY RESTAURANT'),
            (1273, 'KAMUNING BAKERY CORPORATION'),
            (1274, 'OSMIR FARM'),
            (1275, 'DIMENSION DISTRIBUTORS INC.'),
            (1276, 'MCR BLES FOODS TRADING CO.'),
            (1277, 'KENNY RANKIN GENERAL MERCHANDISE'),
            (1278, 'DCAV TRADING'),
            (1279, 'DLA LEISURE INTERNATIONAL'),
            (1280, 'PANDELTON BAKERIES INC.'),
            (1281, 'DANDS GROCERAMA'),
            (1282, 'PANADERIA TRIGO'),
            (1283, 'JANET PARES HOUSE CORPORATION'),
            (1284, 'FREEDOM STORE'),
            (1285, 'JGST WHEAT ENTERPRISE'),
            (1286, 'KAZIRA, EMILY'),
            (1287, 'CAÑETE ENTERPRISE'),
            (1288, 'SOUTHGATE EXPRESS MKTG., INC.'),
            (1289, 'OSMIR ENTERPRISES'),
            (1290, '3B TRADING'),
            (1291, 'S AND P TRUCKING SERVICES'),
            (1292, 'CLOCK WORX FOOD SPECIALIST INC.'),
            (1293, 'FRONT ROYAL TRADING CORP.'),
            (1294, 'COL. GRAINS SUPPLY'),
            (1295, 'NORUTHMAN ENTERPRISES'),
            (1296, 'JESTRE, ROWENA FLORES'),
            (1297, 'MCE LEISURE (PHILIPPINES)'),
            (1298, 'JADEASIA TRADING CORP'),
            (1299, 'RISING SUN BAKERY SUPPLY'),
            (1300, 'SUPER F TRADING'),
            (1301, 'RELISH BAKING SPECIALIST INC.'),
            (1302, 'SPS LOURDES AND ANDREW CORPORATION'),
            (1303, 'SK NETFRONT ENTERPRISES'),
            (1304, '1765 SANTI MERCHANDISE'),
            (1305, 'BORACAY ALTERNATE PANTRY INC.'),
            (1306, 'MANDH FOOD CORP.'),
            (1307, 'ANGELA V.E. FOODS CORPORATION'),
            (1308, 'JK SALAZAR CORPORATION'),
            (1309, 'JHUN-DUR SARI-SARI STORE'),
            (1310, 'BIG EIGHT FOOD DISTRIBUTOR'),
            (1311, 'ROBIS, WILLARD'),
            (1312, '88 HARVEST BAKERY SUPPLIES AND'),
            (1313, 'DROPBOX INC.'),
            (1314, 'HETALIA, ROSENDO S.'),
            (1315, 'JOSHUA BREAD HOUSE'),
            (1316, 'UNIQUE MOSIMO TRADING CORPORATION'),
            (1317, 'WIZARD MANPOWER AND ALLIED'),
            (1318, 'T.H.E BAKER COMPANY INC.'),
            (1319, 'BENITEZ, RUEL JOSEPH ALTA'),
            (1320, 'EBG SUPERMARKET STORES CORPORATION'),
            (1321, 'JOEY SUPERMARKET'),
            (1322, 'NOVAWOOD FOREST INDUSTRIES'),
            (1323, 'JUNROS SERVICES COMPANY'),
            (1324, 'BULLWARK TRANSPORT SYSTEM'),
            (1325, 'SAMONTE, DIANE LAMPAZ'),
            (1326, 'SVC DYNAMIC GRAINS INC.'),
            (1327, 'MONTENEGRO SHIPPING LINES, INC.'),
            (1328, 'GOODFORCE TRADING, INC.'),
            (1329, 'MARIANING AND SONS DEVELOPMENT'),
            (1330, 'TANZIBAR TRUCKING SERVICES'),
            (1331, 'LAURIO, MARICON'),
            (1332, 'MANCILLA, SHEENA MARIE'),
            (1333, 'REYES, GENE'),
            (1334, 'DYSTINY CORP.'),
            (1335, 'SUPERADA ENTERPRISES'),
            (1336, 'HAN CAKES AND PASTRIES'),
            (1337, 'BOSTON BAKERS FOOD CONCEPT'),
            (1338, 'ERCRIS GENERAL MERCHANDISING'),
            (1339, 'REGENCY LAGOON RESORT, INC.'),
            (1340, 'SERAPH MANAGEMENT GROUP, INC.'),
            (1341, 'LUMBERA STORE'),
            (1342, 'VCJS FIESTA FOOD PRODUCTS'),
            (1343, 'ATC ENTERPRISES'),
            (1344, 'RGIES DELICACIES'),
            (1345, 'BARTLE BEYL, INC.'),
            (1346, 'GRANTLINE, INC.'),
            (1347, 'KNOXPORT, INC.'),
            (1348, 'DELISCENTS, INC.'),
            (1349, 'THE REAL RAMEN NAZI INC.'),
            (1350, 'EJT TRUCKING SERVICES'),
            (1351, 'JMM BAKESHOP'),
            (1352, 'AYUNGON TRADING'),
            (1353, 'PALMA, JOYCE REYES'),
            (1354, 'CASA LA TORTILLA PHILS. INC.'),
            (1355, 'JOVELITA M. AVELINO STORE'),
            (1356, 'ALBANO STORE'),
            (1357, 'SOUTH PARK NOODLE HOUSE INC'),
            (1358, 'STARLIGHT TRADING'),
            (1359, 'GROBEST FEEDS PHILIPPINES, INC.'),
            (1360, 'DAVID TRUCKING SERVICE'),
            (1361, 'DLD COMMODITIES TRADING'),
            (1362, 'YAN YAN INTERNATIONAL PHILIPPINES'),
            (1363, 'CENTRAL CHEM INC.'),
            (1364, 'BATANGAS PAPER CORPORATION'),
            (1365, 'NEW FOOD INTERNATIONAL'),
            (1366, 'DON JP TRUCKING SERVICES'),
            (1367, 'CYN CYN FOOD PRODUCTS'),
            (1368, 'RCM TRUCKING SERVICES'),
            (1369, 'PUREBLENDS CORPORATION'),
            (1370, 'BAGONG PAG-ASA BAKERY'),
            (1371, 'AJUY (ILOILO) DEVELOPMENT CORPORATI'),
            (1372, 'TORRES TRADING CO., INC.'),
            (1373, 'FORTUNE NOODLE ENTERPRISES'),
            (1374, 'ZOSIMO FOODS'),
            (1375, 'RCJE TRUCKING SERVICES'),
            (1376, 'FRABELLE CORPORATION'),
            (1377, 'PEAKSUN FLOUR HAULERS CORPORATION'),
            (1378, 'MWS TRUCKING SERVICES'),
            (1379, 'MACROASIA CATERING SERVICES INC.'),
            (1380, 'LOTS A PIZZA FRANCHISE SYSTEMS INC'),
            (1381, 'DOUGHMATE MANUFACTURING AND TRADING'),
            (1382, 'DOUGHPRO MANUFACTURING AND TRADING'),
            (1383, 'FOODCRAFTERS INC.'),
            (1384, 'PONCE, MARICAR G.'),
            (1385, 'JAPSON, JOSELITO'),
            (1386, 'CABATO, ROGER'),
            (1387, 'REGIO, FRANCIS'),
            (1388, 'MAYOL, VERNON A.'),
            (1389, 'LTHFOOD INDUSTRIES INC.'),
            (1390, 'FAST CONSOLIDATED TRANSPORT CORP.'),
            (1391, 'THE GOLDENTREE FOOD INC.'),
            (1392, 'UYGONGCO FOUNDATION INC'),
            (1393, 'DARNIE TRANSPORT'),
            (1394, 'ST. VINCENT LOGISTICS SERVICES'),
            (1395, 'BLACKPANTHER FREIGHT SERVICES'),
            (1396, 'BERNANOS TRADING'),
            (1397, 'JAPANBAKING INC.'),
            (1398, 'CEBU LA MANRE MOVERS INC.'),
            (1399, 'PHAT B ENTERPRISES'),
            (1400, 'C.W.L.T. TRUCKING SERVICES'),
            (1401, 'HELPING HANDS CONSUMERS COOPERATIVE'),
            (1402, 'LUNCH BUCKS GOURMET INC.'),
            (1403, 'EOMONG FOOD DISTRIBUTOR'),
            (1404, 'RJGM PACIFIC CORPORATION'),
            (1405, 'MANG JOSE MAINIT NA PANDESAL'),
            (1406, 'ZM CONDE TRADING'),
            (1407, 'DOUBLEGEM HOTELS AND RESORT,'),
            (1408, 'HT TRUCKING'),
            (1409, 'JGMR TRADING'),
            (1410, 'ARNOLD AND MICHELLE GENERAL'),
            (1411, 'MAIN BAKING SUPPLIES, THE'),
            (1412, 'CPRP MANUFACTURING'),
            (1413, 'AA PRESERVES MANUFACTURING AND'),
            (1414, 'L. LU JR TRUCKING SERVICES'),
            (1415, 'FLAVIANO TRUCKING AND SERVICES'),
            (1416, 'BONNIE TRUCKING'),
            (1417, 'SEASIA LOGISTICS PHILIPPINES, INC.'),
            (1418, 'BNC INGREDIENTS'),
            (1419, 'COSMETIQUE ASIA CORPORATION'),
            (1420, 'REBEL ALLIANCE FOOD SUPPLY, INC.'),
            (1421, 'THE BAKERYCENTER INC.'),
            (1422, '27 STAR TRADING'),
            (1423, 'NEL AND NENG SARI-SARI STORE'),
            (1424, 'KSK FOOD PRODUCTS'),
            (1425, 'JCPA TRADING'),
            (1426, 'DOYEN F1 LOGISTICS INC.'),
            (1427, 'DURINA ENTERPRISE'),
            (1428, 'Z TRUCKING'),
            (1429, 'RS JUSTINIANI TRANSPORT SERVICES'),
            (1430, 'DELA CRUZ, JOELINA'),
            (1431, 'DAVID AGRICULTURAL CORPORATION'),
            (1432, 'E-GLORY BAKERY AND GROCERY'),
            (1433, 'ABS GENERAL MERCHANDISE'),
            (1434, 'SYT BAKESHOP INC.'),
            (1435, 'MARIANO, JOCELYN'),
            (1436, 'PHILIPPINE SOCIETY OF BAKING, INC.'),
            (1437, 'GRACELAND FOOD INDUSTRIES, INC.'),
            (1438, 'TERZA DIMSUM'),
            (1439, 'LDL LOGISTICS'),
            (1440, 'WHITE RIM LOGISTIC CORPORATION'),
            (1441, 'AKLAN CITIZEN BAZAR'),
            (1442, 'RJV RESTAURANT GROUP OF COMPANIES'),
            (1443, 'ADVANCE FOOD CONCEPTS MANUFACTURING'),
            (1444, 'SANDOVAL, RIZZA F.'),
            (1445, 'MIGUELITOS INTERNATIONAL'),
            (1446, 'VELFRAM FOODS CORPORATION'),
            (1447, 'TIMSTATE FOOD AND BEVERAGES'),
            (1448, 'HOKKIE DIMSUM CORP.'),
            (1449, 'SARMIENTO, EDGAR CRUZ'),
            (1450, 'L.C. BIG MAK BURGER INC.'),
            (1451, 'LA VIVA BAKERY SUPPLIES'),
            (1452, 'LA CARLOTA FOOD ENTERPRISE'),
            (1453, 'AMANG ROGER AGRIVET SUPPLY'),
            (1454, 'A.R.C.K. TRADING'),
            (1455, 'R AND I BAKERY SUPPLIES'),
            (1456, 'RNL SIOPAO DELIGHT'),
            (1457, 'EB PARILLA TRUCKING SERVICES'),
            (1458, 'OCEAN TRANSPORT GROUP OF COMPANIES'),
            (1459, 'JSTY TRUCKING/ HAULING SERVICES'),
            (1460, 'DOUGHBAKE INC.'),
            (1461, 'LIPENO TRADING CORPORATION'),
            (1462, 'HOHOHO TRADING CORPORATION'),
            (1463, 'NANGKA BREAD STOP'),
            (1464, 'ANJONG PANDENETE PANADERIA'),
            (1465, 'CENTENNIAL FOOD CORPORATION'),
            (1466, 'JL AND JUSTIN TRADING'),
            (1467, 'SOUTH DIVI LJAY TRADING'),
            (1468, 'KATELINE TRUCKING'),
            (1469, 'DIENGHO TRADING'),
            (1470, 'VIRGILIO B. PILAPIL BAKERY SUPPLIES'),
            (1471, 'SOURCE INTERPACIFIC FOOD CORP.'),
            (1472, 'HENSON, MICHAEL ADRIANO'),
            (1473, 'DISCOVERY PRIMEA'),
            (1474, 'DAN MARKETING'),
            (1475, 'ELICAS TRADING CORP.'),
            (1476, 'BAKERS BAZAAR'),
            (1477, 'QYC MANUFACTURING FOOD IMPORT AND'),
            (1478, 'RADA, MA. HAZEL'),
            (1479, 'EANNE YEANNE ONG LIN'),
            (1480, 'CENTRAL CORRUGATED BOX'),
            (1481, 'SEVERINO M. ALFONSO TRUCKING');   

            SET IDENTITY_INSERT companies OFF;
        ");

        $this->command->info('Users table seeded batch 2');
    }
}
